apiVersion: v1
kind: Service
metadata:
  name: trips
  labels:
    app: trips
spec:
  selector:
    app: trips
  ports:
  - port: 80
    name: http
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  selector:
    app: userprofile
  ports:
  - port: 8080
    name: http
    targetPort: 8080 
