apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
  namespace: api-dev

spec:
  replicas: 3
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryhjd6641.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqluser
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqlpassword
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqlserver
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqldbname