apiVersion: v1
kind: Service
metadata:
  name: tripviewer-internal-service
  namespace: web-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: tripviewer
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer