apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile

spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryhjd6641.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 8080
        env:
        - name: SQL_USER
          value: "sqladminhJd6641"
        - name: SQL_PASSWORD
          value: "sqlpassw0rd123!"
        - name: SQL_SERVER
          value: "sqlserverhjd6641.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
