apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile

spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryhjd6641.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqluser
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqlpassword
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqlserver
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: sqldbname