apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java

spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryhjd6641.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminhJd6641"
        - name: SQL_PASSWORD
          value: "sqlpassw0rd123!"
        - name: SQL_SERVER
          value: "sqlserverhjd6641.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
